
[project]
name = "algo_trading"
version = "0.1"
description = ""
authors = [
    {name = "Madushika Pramod", email = "madushika4@gmail.com"},
]
dependencies = [
    "backtrader>=1.9.78.123",
    "pandas>=2.0.3",
    "Matplotlib>=3.7.2",
    "plotly>=5.15.0",
    "bokeh>=3.2.0",
    "mplcursors>=0.5.2",
    "dash>=2.11.1",
    "statsmodels>=0.14.0",
    "sympy>=1.12",
]
requires-python = ">=3.11"
license = {text = "MIT"}

[tool.pdm]
src_layout = true

[tool.pdm.scripts]
test = "python -m unittest discover"